/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 99e10ccb8d552226317f4903f25c4057)
interface __BaseEnv_Env {
	FORM_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	SITE_URL: string;
	PUBLIC_CONTACT_EMAIL: string;
	RESEND_API_KEY: string;
	RESEND_FROM: string;
	RESEND_REPLY_TO: string;
	QEC_EDITOR_EMAIL: string;
	PUBLIC_POSTHOG_KEY: string;
	PUBLIC_POSTHOG_HOST: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "PUBLIC_CONTACT_EMAIL" | "RESEND_API_KEY" | "RESEND_FROM" | "RESEND_REPLY_TO" | "QEC_EDITOR_EMAIL" | "PUBLIC_POSTHOG_KEY" | "PUBLIC_POSTHOG_HOST">> {}
}
